#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
export _JAVA_AWT_WM_NONREPARENTING=1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a WebCord desktop='^4'
bspc rule -a mpv state=floating
