#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
xcompmgr -c &
xset r rate 300 50 &

# picom -b &
/usr/lib/polkit-kde-authentication-agent-1 &
export _JAVA_AWT_WM_NONREPARENTING=1 &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/Pictures/wallpapers/wallpapers/maller/deep-dark.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a WebCord desktop='^4'
bspc rule -a mpv state=floating
bspc rule -a discord-screenaudio='^5'
